spring:
  datasource: # Datasource
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: h2test 
    password: h2test 
  jpa: # JPA 
    generate-ddl: true 
    open-in-view: false 
    hibernate: 
      ddl-auto: create-drop 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info
    com.bahwa.aop.ExecuteTimeAop: debug