spring:
  servlet:
    multipart:
      max-file-size: 10MB # total file size cannot exceed 10MB. 
      max-request-size: 20MB # total request size for a multipart/form-data cannot exceed 20MB. 
  datasource: # Datasource
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: h2test 
    password: h2test 
  jpa: # JPA 
    generate-ddl: true 
    open-in-view: false 
    hibernate: 
      ddl-auto: create-drop 
    properties: 
      hibernate: 
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    com.bahwa.aop.ExecuteTimeAop: debug
    org.hibernate.type.description.sql: trace

file:
  upload:
    root: "/dev/tmp/upload"