/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bahwa;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class NoticeApp {
    
    public static void main(String[] args) {
		SpringApplication.run(NoticeApp.class, args);
	}
}
