/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bahwa;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.scheduling.annotation.EnableAsync;

@EnableAspectJAutoProxy
@SpringBootApplication
@EnableJpaAuditing
@EnableAsync
public class NoticeApp {
    
    public static void main(String[] args) {
		SpringApplication.run(NoticeApp.class, args);
	}
}
