/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bahwa;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class NoticeAppTest {

    @Test
	void contextLoads() {
	}
}
